// Builds data/kanjivg.js: the stroke paths of every kanji in data/K*.js, taken from
// KanjiVG (https://kanjivg.tagaini.net, CC BY-SA 3.0). Kanji already in the file are kept.
// Usage: node tools/kanjivg.js
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const DATA = path.join(__dirname, "..", "data");
const OUT = path.join(DATA, "kanjivg.js");
const SOURCE = "https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/";

function run(file, api) {
  vm.runInNewContext(fs.readFileSync(file, "utf8"), api);
}

(async () => {
  const kanji = [];
  for (const f of fs.readdirSync(DATA).filter((f) => /^K.*\.js$/.test(f)).sort()) {
    run(path.join(DATA, f), { registerKanji: (id, title, list) => list.forEach((k) => kanji.push(k.k)) });
  }
  const strokes = {};
  if (fs.existsSync(OUT)) run(OUT, { registerStrokes: (s) => Object.assign(strokes, s) });

  for (const k of new Set(kanji)) {
    if (strokes[k]) continue;
    const name = k.codePointAt(0).toString(16).padStart(5, "0") + ".svg";
    const res = await fetch(SOURCE + name);
    if (!res.ok) throw new Error(`${k}: ${name} → HTTP ${res.status}`);
    const paths = [...(await res.text()).matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
    if (!paths.length) throw new Error(`${k}: no strokes found in ${name}`);
    strokes[k] = paths;
    console.log(`${k}  ${paths.length} strokes`);
  }

  const body = Object.entries(strokes)
    .map(([k, p]) => `  "${k}": [\n${p.map((d) => `    ${JSON.stringify(d)},`).join("\n")}\n  ],`)
    .join("\n");
  fs.writeFileSync(OUT,
    "// Kanji stroke paths from KanjiVG (https://kanjivg.tagaini.net), © Ulrich Apel, CC BY-SA 3.0.\n" +
    "// Generated by tools/kanjivg.js. Do not edit by hand.\n" +
    `registerStrokes({\n${body}\n});\n`);
  console.log(`${Object.keys(strokes).length} kanji in data/kanjivg.js`);
})();
